### ISSUE TITLE
missing "DEFINE" statement 

### ISSUE THREAD

**Issue by claudiovercesi** [flaiker/abap-st3#2]
the following statement is missing:
DEFINE 
END-OF-DEFINITION

I solved replacing the followings on file "ABAP.tmLanguage":
			`<string>(?i)^\s*(class|method|form)\s+(?=[a-z_][a-z_0-9])</string>`
with
			`<string>(?i)^\s*(class|method|form|define)\s+(?=[a-z_][a-z_0-9])</string>`
and for the end statement replace
			`<string>(?i)(endclass|endmethod|endform)</string>`
with
			`<string>(?i)(endclass|endmethod|endform|end-of-definition)</string>`

**Comment by flaiker** [comment]
hi, thanks!
Maintaining the ABAP.tmLanguage file is a bit tricky since there is no central one and rather it gets copied on a project by project basis.
I'll add your additions to this one and look for a possible way to get things more centralized.
